#ifndef MAX_PIXEL_VALUE
#define MAX_PIXEL_VALUE (65535)
#endif // !MAX_PIXEL_VALUE

#ifndef FRAME_HEADER_LENGTH
#define FRAME_HEADER_LENGTH (16)
#endif // !FRAME_HEADER_LENGTH

#ifndef MAX_DETECTED_TARGET_COUNT
#define MAX_DETECTED_TARGET_COUNT (3)
#endif // !MAX_DETECTED_TARGET_COUNT

#ifndef TARGET_WIDTH_MAX_LIMIT
#define TARGET_WIDTH_MAX_LIMIT (20)
#endif // !TARGET_WIDTH_MAX_LIMIT

#ifndef TARGET_HEIGHT_MAX_LIMIT
#define TARGET_HEIGHT_MAX_LIMIT (20)
#endif // !TARGET_HEIGHT_MAX_LIMIT
