#ifndef FRAME_COUNT_ONE_ROUND
#define FRAME_COUNT_ONE_ROUND (171)
#endif

#ifndef MOST_DETECED_TARGET_COUNT
#define MOST_DETECED_TARGET_COUNT (3)
#endif

#ifndef SEARCH_TARGET_COUNT_ONE_ROUND
#define SEARCH_TARGET_COUNT_ONE_ROUND (MOST_DETECED_TARGET_COUNT * FRAME_COUNT_ONE_ROUND)
#endif

#ifndef FRAME_COUNT_WHICH_MOST_LIKELY_HAVE_TARGETS
#define FRAME_COUNT_WHICH_MOST_LIKELY_HAVE_TARGETS (3)
#endif